class TestLimits:
    TITLE_MAX_LENGTH = 50
    TITLE_MIN_LENGTH = 5
    CONTENT_MAX_LENGTH = 1500
    SLUG_MAX_LENGTH = 32
    STATUS_MAX_LENGTH = 30

    MAX_TESTS_FOR_USER = 10
    MAX_TEST_TAGS = 4
    SIMILAR_TESTS_LIMIT = 4


class TagLimits:
    MAX_TITLE = 24


class RatingLimits:
    MIN_VALUE = 0
    MAX_VALUE = 5


class QuestionLimits:
    TITLE_MAX_LENGTH = 350

    MIN_ANSWERS_COUNT = 2
    MIN_CORRECT_ANSWERS_COUNT = 1

    TF_MIN_ANSWERS_COUNT = 1
    SC_CORRECT_ANSWERS_COUNT = 1


class AnswerLimits:
    MAX_TITLE_LENGTH = 299
