# Generated by Django 5.2.13 on 2026-05-24 15:17

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='Тег')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['name'], name='tag_name_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название теста')),
                ('content', models.CharField(blank=True, default='Нет описания', max_length=1500, verbose_name='Описание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('slug', models.CharField(max_length=32, unique=True, verbose_name='Альт.название')),
                ('rating_avg', models.FloatField(default=0, verbose_name='Оценка')),
                ('rating_count', models.IntegerField(default=0, verbose_name='кол-во оценок')),
                ('completion', models.IntegerField(default=0, verbose_name='Количество прохождений')),
                ('status', models.CharField(choices=[('published', 'Опубликовано'), ('unpublished', 'Не опубликовано')], default='unpublished', max_length=30, verbose_name='Статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ManyToManyField(blank=True, related_name='tests', to='tests.tag', verbose_name='Теги')),
            ],
            options={
                'ordering': ['-completion'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=350, verbose_name='Вопрос')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('type', models.CharField(choices=[('SC', 'Один вариант'), ('MC', 'Несколько вариантов'), ('TF', 'Текстовое поле')], default='SC', max_length=2, verbose_name='Тип вопроса')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.test', verbose_name='Связанный тест')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=299, verbose_name='Ответ')),
                ('flag', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.question', verbose_name='Связанный вопрос')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['flag'], name='tests_answe_flag_cc6521_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['completion'], name='tests_test_complet_fd2524_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['status', 'author'], name='tests_test_status_56a520_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='test_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='test',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content'], name='test_content_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['type'], name='tests_quest_type_6e70af_idx'),
        ),
    ]
