# Generated by Django 5.2.13 on 2026-04-18 10:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=350, verbose_name='Вопрос')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('type', models.CharField(choices=[('SC', 'Один вариант'), ('MC', 'Несколько вариантов'), ('TF', 'Текстовое поле')], default='SC', max_length=2, verbose_name='Тип вопроса')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='Тег')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название теста')),
                ('content', models.CharField(blank=True, default='Нет описания', max_length=1500, verbose_name='Описание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('slug', models.CharField(max_length=32, unique=True, verbose_name='Альт.название')),
                ('rating_avg', models.FloatField(default=0, verbose_name='Оценка')),
                ('rating_count', models.IntegerField(default=0, verbose_name='кол-во оценок')),
                ('completion', models.IntegerField(default=0, verbose_name='Количество прохождений')),
                ('status', models.CharField(choices=[('published', 'Опубликовано'), ('unpublished', 'Не опубликовано')], default='unpublished', max_length=30, verbose_name='Статус')),
            ],
            options={
                'ordering': ['-completion'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('correct_answers', models.PositiveIntegerField(verbose_name='Правильные ответы')),
                ('total_questions', models.PositiveIntegerField(verbose_name='Всего вопросов')),
                ('uuid_slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Результат теста',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=299, verbose_name='Ответ')),
                ('flag', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.question', verbose_name='Связанный вопрос')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
