# Generated by Django 5.2.13 on 2026-08-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='tag',
            new_name='tags',
        ),
    ]
