# Generated by Django 5.2.13 on 2026-04-18 10:47

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='tag_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddField(
            model_name='test',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tests', to='tests.tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='rating',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='tests.test'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.test', verbose_name='Связанный тест'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tests.test'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['flag'], name='tests_answe_flag_cc6521_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['completion'], name='tests_test_complet_fd2524_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['status', 'author'], name='tests_test_status_56a520_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='test_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='test',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content'], name='test_content_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'test')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['type'], name='tests_quest_type_6e70af_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['test'], name='tests_testr_test_id_01a254_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['user'], name='tests_testr_user_id_f3d3d4_idx'),
        ),
    ]
