# Generated by Django 5.2.13 on 2026-04-18 10:53
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_initial'),
    ]

    operations = [
        TrigramExtension(),
    ]
